### ISSUE TITLE
Theoretical Thoughts

### ISSUE THREAD

**Issue by KingKannibal** [psakhis/Groovy_MiSTer#1]
I haven't gotten around to getting it working yet, but the premise of Groovy MiSTer is really thought provoking. Would people be able to start using the MiSTer to display other software or games? I had VLC and MUGEN/Ikemen in mind, possibly other open source games.

**Comment by psakhis** [comment]
For the moment, the best chance is with WindowCast core from retroarch.

**Comment by psakhis** [comment]
MiSTerCast is the way to go.
