### ISSUE TITLE
[Feature] GUI or Graphical Widget I Support for Retroarch's On-Screen Notifications 

### ISSUE THREAD

**Issue by Daddu3** [psakhis/Groovy_MiSTer#10]
Been requesting few times on Discord but essentially, GUI notifications (and I suppose text?) don't get outputted on Groovy MiSTer's end from Retroarch. This robs us useful notifications for RetroAchievements or counters for framerate

I heard that they work via hardware-based cores, but there aren't too many left on that also support Retroachivements, I think.

**Comment by psakhis** [comment]
Please try new build with mister_force_scaler to "true"

**Comment by Daddu3** [comment]
> Please try new build with mister_force_scaler to "true"

Working as intended!
