### ISSUE TITLE
[Feature request] Linux and Steam support ?

### ISSUE THREAD

**Issue by Saroumane** [psakhis/Groovy_MiSTer#3]
Hello, I just saw your presentation video, it seems to work amazingly well, kudos !

So I have 2 questions :

Is it planned to support mame and retroarch linux/wayland builds ?

Steam has many new excellent 2D games (natively running in 240p or close to it). It would be fantastic if we could stream them to Groovy MiSTer CRT core.
What do you think about it ?

**Comment by zyzlj** [comment]
It's not possible. pc game even 2d games is too much pressure to mister, graphic card is necessary

**Comment by Saroumane** [comment]
Well, I can happily report it "just works" on Linux, with wine. (wine 9.3)
I placed Groovy.rbf (in Utility folder) and replaced the MiSTer menu.
I used the mame "no gpu" build provided with the flags provided : 
`$ wine mame.exe -video mister -aspect 4:3 -switchres -monitor arcade_15 -mister_window -mister_ip "192.x.x.x" -mister_compression lz4 -skip_gameinfo -syncrefresh -nothrottle`
(Of course you have to use the real IP of your MiSTer FPGA)

**Comment by psakhis** [comment]
On Linux it's important set a udp send buffer like  "sysctl net.core.wmem_max=2097152"

**Comment by Saroumane** [comment]
> On Linux it's important set a udp send buffer like "sysctl net.core.wmem_max=2097152"

Sometimes during my first tests, the picture became a bit blurry. Could it be a fix for this ? (I did not try to modify any settings on the Groovy core itself)
