### ISSUE TITLE
send input does not work in retroarch

### ISSUE THREAD

**Issue by xenyou** [psakhis/Groovy_MiSTer#7]
it seems that retroarch can not be controlled by send input.

i'm using this latest version of retroarch.

https://github.com/psakhis/Groovy_MiSTer/tree/main/test-builds/20240427

And boot is okay. I can see the screen in MiSter.
```
.\retroarch.exe -L .\cores\opera_libretro.dll --menu
```

But I can not controll retroarch with mister attached controller.

I also checked mame. And mame works with the controller.

**Comment by psakhis** [comment]
Hi, do you set mister (instead of xinput) as joypad_driver and configured buttons?

**Comment by xenyou** [comment]
Yes. I'll attach my config.

[retroarch.cfg.txt](https://github.com/psakhis/Groovy_MiSTer/files/15170796/retroarch.cfg.txt)

By the way, I copied the latest retroarch_win64.7z(retroarch.exe) to the official retroarch(nightly).

I got the base version of retroarch here.
https://www.retroarch.com/?page=platforms

Is it ok? Or I need to get like groovy_retroarch?

**Comment by psakhis** [comment]
Do you configured mappings?
Menu -> Settings -> Input -> Port1 Controls

**Comment by xenyou** [comment]
Thanks. I've configured port1 controls and now it works!!!!

Yeeeeeeees!!!! (3DO port)
![Screenshot 2024-05-02 at 18 09 50](https://github.com/psakhis/Groovy_MiSTer/assets/832358/988dcd8d-872c-41ce-b2fe-35cdbe449594)
