### ISSUE TITLE
0.4 does not boot

### ISSUE THREAD

**Issue by xenyou** [psakhis/Groovy_MiSTer#9]
I just tried the latest version.
https://github.com/psakhis/Groovy_MiSTer/releases/tag/v0.4

But the groovy logo did not show.

I followed these steps except the last one(XDP thing).
https://github.com/psakhis/Groovy_MiSTer?tab=readme-ov-file#installation-transfers-in-binary-mode

This step is always required?
> Only for XDP high performance feature, some tweaks on Linux are needed. For UDP isn't needed.

**Comment by psakhis** [comment]
Which connection are you using? VGA/Hdmi direct video

Can you share your MiSTer.ini?

**Comment by xenyou** [comment]
here is my config. I'm using VGA.

[MiSTer.ini.txt](https://github.com/user-attachments/files/16319768/MiSTer.ini.txt)

**Comment by psakhis** [comment]
It's rare, with your file is working here.
Can you try combining binary and rbf?
 - Old MiSTer_groovy and new Groovy.rbf
 - New MiSTer_groovy and old Groovy.rbf

**Comment by xenyou** [comment]
result is here. 

- old mister-groovy and new groovy.rbf : work
- new mister-groovy and old groovy.rbf : not work

I used this version as old ones.
https://github.com/psakhis/Groovy_MiSTer/tree/main/test-builds/20240616

**Comment by psakhis** [comment]
Interesting, so seems main.

Can you test new MiSTer_groovy deleting /media/fat/config/Groovy.CFG?

In theory, all options by default loads UDP.

If not work, i will try to revert XDP part from my Linux installation to see if main for some reason isn't working with XDP support.

**Comment by xenyou** [comment]
> Can you test new MiSTer_groovy deleting /media/fat/config/Groovy.CFG?

I've just tested. And it does not work.

**Comment by psakhis** [comment]
Ok, so seems for some reason needs XDP installation.
You can try to install XDP feature if that fix it. In anycase i will test here reverting XDP installation; idea is XDP will be optional.

**Comment by psakhis** [comment]
I'm thinking it's linked with libelf, so library is needed on /usr/lib

**Comment by xenyou** [comment]
I added libelf.so.1 to /usr/lib/ and it works!!
It seems that this file is always required.

Thanks. I'll close this issue.
